language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly" # currently points to 3.6-dev
  - "pypy"
  - "pypy3"

  
# command to install dependencies
install:
  - pip install codecov
# command to run tests
script:
  - coverage  run  --omit 'tests/*.*' -m py.test

notifications:
  email: false

after_success:
  - codecov
